### ISSUE TITLE
Follow-up 

### ISSUE THREAD

**Issue by Sardor-M** [sardor-mv/react-practice-project#2]
## To-dos 

- [x] Test whether from child to parent component data transferring is working or not properly.
- [x] Declare UsernameListItem component and finish its styling work as well 
- [x]  Check the validation of the UserInput in different values. 

**Note: This is a React practice based project**

**Comment by Sardor-M** [comment]
Finished the today's mission 💯
